_core:
  default_config_hash: 71vTnk5szuOQRTsOR-S5bjCzPvkxtx_eVGMqYa_mcqc
schemas:
  bootstrap: 8000
  ecommerce: 8000
favicon:
  mimetype: image/png
  path: 'public://Logo sin fondo.png'
  url: /themes/custom/ecommerce/favicon.ico
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://Logo si fondo.png'
  url: ''
  use_default: 0
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
apply: Aplicar
reset_http_request_cache: ''
table: ''
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
  iconos: ''
langcode: es
